# Understanding the `numpy.ndarray` internals

In [1]:
import numpy as np

In [2]:
x = np.array([[0, 1, 2, 3],[4, 5, 6, 7], [8, 9, 10, 11], [12, 13, 14, 15]], dtype=np.int8)
x

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]], dtype=int8)

In [3]:
x.strides

(4, 1)

### Understanding strides

In [4]:
y = x.reshape((2, 8))
print(y)
y.strides

[[ 0  1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14 15]]


(8, 1)

In [5]:
z = x.reshape((1, 16))
print(z)
z.strides

[[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]]


(16, 1)

In [6]:
a = np.array([[0, 1, 2, 3],[4, 5, 6, 7],[8, 9, 10, 11], [12, 13, 14, 15]], dtype=np.int16)
print(a)
a.strides

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]


(8, 2)

Both `flatten()` and `ravel()` return a flattend version of an array.

In [7]:
x = np.arange(5)
print('x =', x)

y = x.ravel()  #  assign to y a flattened version the array x
y[0] = 5       #  change the first element of the array y

print('\nx =', x)

x = [0 1 2 3 4]

x = [5 1 2 3 4]


In [8]:
x = np.random.rand(5000, 5000)

The next three cells do the same two operations: transposing a matrix and flattening it.

In [9]:
%%timeit

x.T
x.ravel()

436 ns ± 16 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)


In [10]:
%%timeit

x.T
x.flatten()

118 ms ± 4.14 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [11]:
%%timeit

x.T.ravel()

557 ms ± 40.4 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


Where the difference in execution time came form?

``ravel()``:
Returns only reference/view of original array.
If we modify the array we would notice that the value of original array also changes.
``ravel()`` is faster than ``flatten()`` as it does not occupy any memory.
``ravel()`` is a library-level function.

``flatten()``:
Return copy of original array.
If we modify any value of this array value of original array is not affected.
``flatten()`` is comparatively slower than ``ravel()`` as it occupies memory.
``flatten()`` is a method of an ``ndarray`` object. 