### Intro to linear algebra with numpy

In [1]:
import numpy as np

from numpy.linalg import solve, inv
from numpy.random import rand

In [2]:
a = np.array([[1, 3, 5], [3, 7, 9], [3, 11, 13]]) #3x3
b = np.array([7.07, 9.5, 17]) #1x3
c = rand(5, 3) #Polje 5x3 s random vrijednostima

print(c)

[[0.32230458 0.96653189 0.01417707]
 [0.88398645 0.32964595 0.23531107]
 [0.30036329 0.75306594 0.27281728]
 [0.33431345 0.72298005 0.28679152]
 [0.860993   0.08857601 0.75597024]]


In [3]:
print(a.transpose()) #Transponiranje matrice
#(Pretvaranje redaka u stupce)

[[ 1  3  3]
 [ 3  7 11]
 [ 5  9 13]]


In [5]:
print(inv(a)) #Inverz matrice

[[-0.5    1.    -0.5  ]
 [-0.75  -0.125  0.375]
 [ 0.75  -0.125 -0.125]]


In [6]:
print(solve(a,b)) #Rješavanje jednadžbe ax = b   

[-2.535 -0.115  1.99 ]


In [8]:
print(np.linalg.det(a)) #Izračunaj determinantu matrice

15.999999999999998


In [9]:
print(np.linalg.matrix_rank(a)) #Izračunaj rang matrice

3


In [10]:
print(np.linalg.matrix_power(a, 5)) #Dizanje svakog elementa matrice na 5-tu potenciju

[[ 257545  790015  977617]
 [ 516147 1583269 1959243]
 [ 750891 2303341 2850307]]
