# Intro to linear algebra with numpy

In [1]:
import numpy as np

from numpy.linalg import solve, inv
from numpy.random import rand

In [2]:
a = np.array([[1, 3, 5], [3, 7, 9], [3, 11, 13]]) #3x3
b = np.array([7.07, 9.5, 17]) #1x3
c = rand(5, 3) #5x3 with random values

print(c)

[[0.32230458 0.96653189 0.01417707]
 [0.88398645 0.32964595 0.23531107]
 [0.30036329 0.75306594 0.27281728]
 [0.33431345 0.72298005 0.28679152]
 [0.860993   0.08857601 0.75597024]]


The transpose of a matrix is an operator which flips a matrix over its diagonal; that is, it switches the row and column indices of the matrix A by producing another matrix

In [3]:
print(a.transpose()) #Transponing the matrix


[[ 1  3  3]
 [ 3  7 11]
 [ 5  9 13]]


An n-by-n square matrix A is called invertible (also nonsingular or nondegenerate), if there exists an n-by-n square matrix B such that

    ``A B = B A = I n``

where In denotes the n-by-n identity matrix and the multiplication used is ordinary matrix multiplication.

In [5]:
print(inv(a)) #Invers of the matrix

[[-0.5    1.    -0.5  ]
 [-0.75  -0.125  0.375]
 [ 0.75  -0.125 -0.125]]


In [6]:
print(solve(a,b)) #Solving equation ax = b   

[-2.535 -0.115  1.99 ]


The determinant is a scalar value that can be computed from the elements of a square matrix and encodes certain properties of the linear transformation described by the matrix.
Geometrically, it can be viewed as the volume scaling factor of the linear transformation described by the matrix. This is also the signed volume of the n-dimensional parallelepiped spanned by the column or row vectors of the matrix.
The determinant is positive or negative according to whether the linear transformation preserves or reverses the orientation of a real vector space. 


In [8]:
print(np.linalg.det(a)) #Calculate the determinant of the matrix


15.999999999999998


The rank of a matrix A is the dimension of the vector space generated (or spanned) by its columns.
This corresponds to the maximal number of linearly independent columns of A. This, in turn, is identical to the dimension of the vector space spanned by its rows.
Rank is thus a measure of the "nondegenerateness" of the system of linear equations and linear transformation encoded by A. There are multiple equivalent definitions of rank. A matrix's rank is one of its most fundamental characteristics.

In [9]:
print(np.linalg.matrix_rank(a)) #Calculate rank of the matrix


3


In [10]:
print(np.linalg.matrix_power(a, 5)) #To the 5th power


[[ 257545  790015  977617]
 [ 516147 1583269 1959243]
 [ 750891 2303341 2850307]]
